#A Collatz sequence is generated by repeatedly applying the following rules to an integer and then to each resulting integer in turn:
#If even: divide by 2. If odd: multiply by 3, then add 1.
#The Collatz algorithm has been tested and found to always reach 1 for all positive integers.
#Create a function that, when given two positive integers a b, returns the string "a" if integer a took fewer steps to reach 1 than b when passed through the Collatz sequence, or "b" if integer b took fewer steps to reach 1 than a.

a = int(input('Zadej číslo "a": '))
b = int(input('Zadej číslo "b": '))

def Collatz_Con(a, b):
    n = 0
    m = 0
    while a != 1:
        n += 1
        if a % 2 == 0:
            a /= 2
        elif a % 2 != 0:
            a = a * 3 + 1
    while b != 1:
        m += 1
        if b % 2 == 0:
            b /= 2
        elif b % 2 != 0:
            b = b * 3 + 1
    if n < m:
        return ("a")
    elif m < n:
        return ("b")
print(Collatz_Con(a, b))